### ISSUE TITLE
[Fable] support warning

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ArcGraphModel#7]
Just so i don't forget about this:

![image](https://user-images.githubusercontent.com/39732517/233729816-2ba17ad9-fd8c-4c7d-84a9-0d5d4e336da4.png)

![image](https://user-images.githubusercontent.com/39732517/233729859-a7b27537-52d6-4206-8db8-470b5dff640c.png)

**Comment by Freymaurer** [comment]
This also makes fable throw an error in these tests:

```fsharp
let private ExtendedContainer = testList "ExtendedContainer" [

    let version = "0.0.1"
    let protocol = new Protocol()

    do protocol.Version <- version

    testCase "HasValue" (fun _ ->
        let result = Dictionary.containsKey Protocol.VersionProperty protocol
        Expect.isTrue result ""
    )
    testCase "HasOneItem" (fun _ ->
        let result = Dictionary.count protocol
        Expect.equal 1 result ""
    )
    testCase "CanRetrieve" (fun _ ->
        let result = protocol.Version
        Expect.equal version result ""
    )
]
```

![image](https://user-images.githubusercontent.com/39732517/233733339-d2976e71-2ea3-478d-993b-ed10fb046513.png)

Can be seen with `build.cmd watchtestsjs`

**Comment by HLWeil** [comment]
> Just so i don't forget about this:
> 
> ![image](https://user-images.githubusercontent.com/39732517/233729816-2ba17ad9-fd8c-4c7d-84a9-0d5d4e336da4.png)
> 
> ![image](https://user-images.githubusercontent.com/39732517/233729859-a7b27537-52d6-4206-8db8-470b5dff640c.png)
> 

Oh, so you can't use static values for inherited constructors.. That's a bit annoying but maybe we can circumvent it by having an internal primary constructor and calling that with an parameterless alternative constructor.
